---
- name: Install nginx
  apt: name=nginx state=present

- name: Delete default nginx vhost symlink
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: Enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Create htpasswd entry if needed
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ nginx.auth_basic_username }}"
    password: "{{ nginx.auth_basic_password }}"
  when: nginx.auth_basic_username is defined and nginx.auth_basic_password is defined
