---
- name: Install common packages
  hosts: datahub,datahub_pipeline,datahub_dashboard,arthub,resourcespace,cantaloupe,imagehub
  roles:
    - common

- name: Install mariadb
  hosts: resourcespace,imagehub
  roles:
    - mariadb

- name: Install php-fpm and mongodb
  hosts: datahub,datahub_dashboard
  roles:
    - php-fpm
    - mongodb

- name: Install nginx
  hosts: datahub,datahub_dashboard,arthub
  roles:
    - nginx

- name: Install datahub
  hosts: datahub
  roles:
    - datahub

- name: Install datahub pipeline
  hosts: datahub_pipeline
  roles:
    - datahub-pipeline

- name: Install datahub dashboard
  hosts: datahub_dashboard
  roles:
    - datahub-dashboard

- name: Install arthub
  hosts: arthub
  roles:
    - arthub

- name: Install ResourceSpace
  hosts: resourcespace
  roles:
    - resourcespace

- name: Install cantaloupe
  hosts: cantaloupe
  roles:
    - cantaloupe

- name: Install Imagehub
  hosts: imagehub
  roles:
    - imagehub

- name: Setup ResourceSpace
  hosts: resourcespace
  roles:
    - resourcespace_setup

- name: Set up cronjob
  hosts: datahub_pipeline,datahub_dashboard,arthub,imagehub
  roles:
    - cron

- name: Set up SSL Certificates through LetsEncrypt
  hosts: datahub,datahub_dashboard,arthub,imagehub
  roles:
    - name: certbot
      when: letsencrypt_vhosts | length > 0
