---
- name: Configure apt repository if Debian 10
  set_fact:
    mariadb_apt_repository: "deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.6/debian buster main"
  when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '10'

- name: Configure apt repository if Debian 11
  set_fact:
    mariadb_apt_repository: "deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.6/debian bullseye main"
  when: ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version == '11'

- name: Configure apt repository if Ubuntu 18
  set_fact:
    mariadb_apt_repository: "deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.6/ubuntu bionic main"
  when: ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == '18'

- name: Configure apt repository if Ubuntu 20
  set_fact:
    mariadb_apt_repository: "deb [arch=amd64] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.6/ubuntu focal main"
  when: ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == '20'

- name: Add PGP key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc

- name: Add apt repository
  apt_repository:
    repo: "{{ mariadb_apt_repository }}"

