---
- name: Update apt repositories
  apt:
    update_cache: yes

- name: Install git, screen, curl, pip, virtualenv, setuptools, software-properties-common, dirmngr, apt-transport-https and ca-certificates
  apt:
    name:
      - git
      - screen
      - curl
      - software-properties-common
      - dirmngr
      - apt-transport-https
      - ca-certificates

- name: Install python-pip, python-virtualenv, python-setuptools and python-passlib when python 2.*
  apt:
    name:
      - python-pip
      - python-virtualenv
      - python-setuptools
      - python-passlib
  when: ansible_python_version is match("2\..*")

- name: Install python3-pip, python3-virtualenv, python3-setuptools and python3-passlib when python 3.*
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-setuptools
      - python3-passlib
  when: ansible_python_version is match("3\..*")

- name: Create application user if it does not yet exist
  user:
    name: "{{ application_user }}"
    password: "{{ application_password | password_hash('sha512') }}"
    state: present
